csk/urls.py
from django.urls import path
from csk.views import *

app_name='dhoni'

urlpatterns=[
    path('dhoni/',dhoni,name='dhoni')
]

project8/urls.py
from django.contrib import admin
from django.urls import path,include
import csk,rcb
from india.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('csk/',include('csk.urls')),
    path('rcb/',include('rcb.urls')),
    path('sehwag/',sehwag,name='sehwag'),
]

rcb/urls.py
from django.urls import path
from rcb.views import *

app_name='virat'

urlpatterns=[
    path('virat/',virat,name='virat')
]

india/models.py
from django.db import models

# Create your models here.

csk/views.py
from django.shortcuts import render
def dhoni(request):
    return render(request,'dhoni.html')


# Create your views here.

india/views.py
from django.shortcuts import render

def sehwag(request):
    return render(request,'sehwag.html')

# Create your views here.

rcb/views.py
from django.shortcuts import render
def virat(request):
    return render(request,'virat.html')
# Create your views here.

templates/dhoni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is Dhoni</h1>
        <h1><a href="{% url 'virat:virat' %}">Navigate to virat </a></h1>
        <h1><a href="{% url 'sehwag' %}">go to sehwag page</a></h1>
    </center>
</body>
</html>

templates/sehwag.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is sehwag</h1>
        <h1><a href="{% url 'virat:virat' %}">Navigate to virat </a></h1>
        <h1><a href="{% url 'dhoni:dhoni' %}">navigate to dhoni </a> </h1>
    </center>
</body>
</html>

templates/virat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is virat</h1>
        <h1><a href="{% url 'dhoni:dhoni' %}">Navigate to dhoni </a></h1>
    </center>
</body>
</html>